#!/bin/bash

# PAM configuration SSH:
echo "#PAMAC configuration" >> /etc/pam.d/sshd
echo "auth        required     pam_python.so accesscontrol.py" >> /etc/pam.d/sshd
echo "session     required     pam_python.so accesscontrol.py" >> /etc/pam.d/sshd

# PAM configuration XDM:
echo "#PAMAC configuration" >> /etc/pam.d/sddm
echo "auth        required     pam_python.so accesscontrol.py" >> /etc/pam.d/sddm
echo "session     required     pam_python.so accesscontrol.py" >> /etc/pam.d/sddm

# PAM configuration TTY:
echo "#PAMAC configuration" >> /etc/pam.d/login
echo "auth        required     pam_python.so accesscontrol.py" >> /etc/pam.d/login
echo "session     required     pam_python.so accesscontrol.py" >> /etc/pam.d/login


if [ $(arch) == 'i686' ]
then
	cat /usr/share/pamac/pam_python32.so.base64 |base64 -d >/lib/security/pam_python.so
else
	echo x86_64
fi

