#!/bin/bash

sed -i '/accesscontrol/d' /etc/pam.d/sshd
sed -i '/accesscontrol/d' /etc/pam.d/sddm
sed -i '/accesscontrol/d' /etc/pam.d/login


if [ $(arch) == 'i686' ]
then
    echo x86_64
else
    rm -rf /lib/security/pam_python.so
fi
