#!/bin/bash

# PAM configuration for SSH, login(1), sddm, xdm, gdm, kdm and lightdm

for i in "sddm" "login" "sshd" "lightdm" "xdm" "kdm" "gdm"; do
    if [ -f "/etc/pam.d/$i" ]; then
      echo "#PAM-accesscontrol configuration" >> "/etc/pam.d/$i"
      echo "auth        required     pam_python.so accesscontrol.py" >> "/etc/pam.d/$i"
      echo "session     required     pam_python.so accesscontrol.py" >> "/etc/pam.d/$i"
      echo \[DONE\] successfully configured: $i
    fi
done


if [ $(arch) == 'i686' ]
then
	cat /usr/share/pamac/pam_python32.so.base64 |base64 -d >/lib/security/pam_python.so
else
	echo x86_64
fi

