.TH PAM-ACCESSCONTROL "1" "Jan 2018"
.SH NAME
PAM-accesscontrol \- PAM plugin to contol access to host via SSH, tty/login(1) and such
desktop logins like sddm, XDM, KDM, GDM and lightdm.

.SH DESCRIPTION
PAM-ACCESSCONTROL is writen in python and use PAM to control access to the system via Secure
Shell, sddm, kdm, gdm, lightdm, xdm and login(1). It makes it possible to manages access for
some group of users or, for example, depend on configuration can ask you (by using standard
notification window) for confirmation about each new incoming SSH connection.
                                    _________
                     /= Yes/No ==> |PyQt5 win|  <===>  local user
                     |             |_________|
               ______|__________ 
              |                 |                                      +-+-+-+     <--login(1)-->
    ----------|PAM-accesscontrol| <=============> pam_python.so  <===> + PAM +     <---sddm----->   Gast
    |         |_________________|                                      +-+-+-+          SSH----->
    |                   |      |                                         ||              |
    |                   |      |__________                               ||              |
    |                   |                 |                            _________         |
    |                   |                 |                           |  SSH    |        |
 Logfile        Configration file       Syslog        <============== | Server  |  <-----+
                                                                      |_________|

PAM-accesscontrol configuration happen by filling rules to the configuration file.
PAM-accesscontrol uses Syslog for every login-events.

.SH FILES
.TP
.I /var/log/pam-accesscontrol-<JAHR>-<MONAT>.log
Logfile
.TP
.I /etc/pam-accesscontrol.d/*.conf
Configfile
.PP

.SH AUTOR
Writen by Alexander Naumov <alexander_naumov@opensuse.org>

.SH "SEE ALSO"
.BR pam (7),
.BR sddm (1),
.BR sshd (8),
.BR pam-accesscontrol.d (5)
