.TH PAMAC "1" "Juni 2017"
.SH NAME
PAM-accesscontrol \- PAM plugin to contol the access to host via SSH, SDDM and TTY.

.SH DESCRIPTION
PAMAC is writen in python and use PAM to control access to the system via Secure Shell, SDDM and
login(1). It makes it possible to manages access for some group of users or, for example, depend
on configuration can ask you (by using standard notification window) for confirmation about each
new incoming SSH connection.
                                    _________
                      /= Yes/No ==>| KDialog |  <===>   local user
                      |            |_________|
                 _____|__________ 
                |                |                                     +-+-+-+     <----TTY---->
    ----------- |     PAMAC      | <=============> pam_python.so <==>  + PAM +     <----KDM---->   Gast
    |           |________________|                                     +-+-+-+          SSH---->
    |                   |      |                                         ||              |
    |                   |      |__________                               ||              |
    |                   |                 |                            _________         |
    |                   |                 |                           |  SSH    |        |
 Logfile        Configration file       Syslog        <============== | Server  |  <-----+
                                                                      |_________|

PAMAC configuration happen by filling rules to the configuration file.
PAMAC uses Syslog for every login-events.

.SH FILES
.TP
.I /lib/security/pam_python.so
Via this PAM module happen communication between PAM itself and PAM python plugins.
.TP
.I /var/log/pamac-<JAHR>-<MONAT>.log
Logfile
.TP
.I /etc/pam-accesscontrol.d/*.conf
Configurationfile
.PP

.SH AUTOR
Writen by Alexander Naumov <alexander_naumov@opensuse.org>

.SH "SEE ALSO"
.BR pam (7),
.BR sddm (1),
.BR sshd (8),
.BR pam-accesscontrol.d (5)
